<?php

/**
 * $country places/cities/municipalities/districts
 * - $count places/cities/municipalities/districts
 * 
 * Source: 
 * - [Please add the source(s) link(s) to check the list of places]
 * List of Khmer district
 * @author  Your Name Here <yourname@here.com> | https://yourwebsite.com
 * @version 1.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 */

global $places;

$places['KH'] = array(  
  'KH1' => array(
    'Mongkol Borei',
    'Phnum Srok',
    'Preah Net Preah',
    'Ou Chrov',
    'Krong Serei Saophoan',
    'Thma Puok',
    'Svay Chek',
    'Malai',
    'Krong Paoy Paet',
  ),
  'KH2' => array(
    'Banan',
    'Thma Koul',
    'Krong Battambang',
    'Bavel',
    'Aek Phnum',
    'Moung Ruessei',
    'Rotonak Mondol',
    'Sangkae',
    'Samlout',
    'Sampov Lun',
    'Phnom Proek',
    'Kamrieng',
    'Koas Krala',
    'Rukhak Kiri',
  ),
  'KH3'=>array(
    'Batheay',
    'Chamkar Leu',
    'Cheung Prey',
    'Krong Kampong Cham',
    'Kampong Siem',
    'Kang Meas',
    'Kaoh Soutin',
    'Prey Chhor',
    'Srei Santhor',
    'Stueng Trang',
  ),
  'KH4'=>array(
    'Baribour',
    'Chol Kiri',
    'Krong Kampong Chhnang',
    'Kampong Leaeng',
    'Kampong Tralach',
    'Rolea Baier',
    'Sameakki Mean Chey',
    'Tuek Phos',
  ),
  'KH5'=>array(
    'Basedth',
    'Krong Chbar Mon',
    'Kong Pisei',
    'Aoral',
    'Odongk',
    'Phnum Sruoch',
    'Samraong Tong',
    'Thpong',
  ),
  'KH6'=>array(
    'Baray',
    'Kampong Svay',
    'Krong Stueng Saen',
    'Prasat Ballangk',  
    'Prasat Sambour',
    'Sandan',
    'Santuk',
    'Stoung',
    'Taing Kouk District',
  ),
  'KH7'=>array(
    'Angkor Chey',
    'Banteay Meas',
    'Chhuk',
    'Chum Kiri',
    'Dang Tong',
    'Kampong Trach',
    'Tuek Chhou',
    'Krong Kampot',
  ),
  'KH8'=>array(
    'Kandal Stueng',
    'Kien Svay',
    'Khsach Kandal',
    'Kaoh Thum',
    'Leuk Daek',
    'Lvea Aem',
    'Mukh Kampul',
    'Angk Snuol',
    'Ponhea Lueu',
    'S Ang',
    'Krong Ta Khmau',
  ),
  'KH9'=>array(
    'Botum Sakor',
    'Kiri Sakor',
    'Kaoh Kong',
    'Krong Khemarak Phoumin',
    'Mondol Seima',
    'Srae Ambel',
    'Thma Bang',
  ),
  'KH10'=>array(
    'Chhloung',
    'Krong Kracheh',
    'Preaek Prasab',
    'Sambour',
    'Snuol',
    'Chitr Borie',
  ),
  'KH11'=>array(
    'Kaev Seima',
    'Kaoh Nheaek',
    'Ou Reang',
    'Pech Chreada',
    'Krong Saen Monourom',
  ),
  'KH12'=>array(
    'Chamkar Mon ',
    'Doun Penh ',
    'Prampir Meakkakra ',
    'Tuol Kouk ',
    'Dangkao ',
    'Mean Chey ',
    'Russey Keo ',
    'Saensokh ',
    'Pur SenChey ',
    'Chraoy Chongvar ',
    'Praek Pnov ',
    'Chbar Ampov ',
    'Boeng Keng Kang ',
    'Kamboul ',
  ),
  'KH13'=>array(
    'Chey Saen',
    'Chhaeb',
    'Choam Khsant',
    'Kuleaen',
    'Rovieng',
    'Sangkum Thmei',
    'Tbaeng Mean Chey',
    'Krong Preah Vihear',
  ),
  'KH14'=>array(
    'Ba Phnum',
    'Kamchay Mear',
    'Kampong Trabaek',
    'Kanhchriech',
    'Me Sang',
    'Peam Chor',
    'Peam Ro',
    'Pea Reang',
    'Preah Sdach',
    'Krong Prey Veng',
    'Kampong Leav',
    'Sithor Kandal',
    'Svay Antor',
  ),
  'KH15'=>array(
    'Bakan',
    'Kandieng',
    'Krakor',
    'Phnum Kravanh',
    'Krong Pursat',
    'Veal Veaeng',
    'Ta Lou Senchey',
  ),
  'KH16'=>array(
    'Andoung Meas',
    'Krong Ban Lung',
    'Bar Kaev',
    'Koun Mom',
    'Lumphat',
    'Ou Chum',
    'Ou Ya Dav',
    'Ta Veaeng',
    'Veun Sai',
  ),
  'KH17'=>array(
    'Angkor Chum',
    'Angkor Thum',
    'Banteay Srei',
    'Chi Kraeng',
    'Kralanh',
    'Puok',
    'Prasat Bakong',
    'Krong Siem Reab',
    'Soutr Nikom',
    'Srei Snam',
    'Svay Leu',
    'Varin',
  ),
  'KH18'=>array(
    'Krong Preah Sihanouk',
    'Prey Nob',
    'Stueng Hav',
    'Kampong Seila',
    'Krong Kaoh Rung',
  ),
  'KH19'=>array(
    'Sesan',
    'Siem Bouk',
    'Siem Pang',
    'Krong Stueng Traeng',
    'Thala Barivat',
    'Borei Ou Svay Senchey',
  ),
  'KH20'=>array(
    'Chantrea',
    'Kampong Rou',
    'Rumduol',
    'Romeas Haek',
    'Svay Chrum',
    'Krong Svay Rieng',
    'Svay Teab',
    'Krong Bavet',
  ),
  'KH21'=>array(
    'Angkor Borei',
    'Bati',
    'Borei Cholsar',
    'Kiri Vong',
    'Kaoh Andaet',
    'Prey Kabbas',
    'Samraong',
    'Krong Doun Kaev',
    'Tram Kak',
    'Treang',
  ),
  'KH22'=>array(
    'Anlong Veaeng',
    'Banteay Ampil',
    'Chong Kal',
    'Krong Samraong',
    'Trapeang Prasat',
  ),
  'KH23'=>array(
    'Damnak Chang Aeur',
    'Krong Kaeb',
  ),
  'KH24'=>array(
    'Krong Pailin',
    'Sala Krau',
  ),
  'KH25'=>array(
    'Dambae',
    'Krouch Chhmar',
    'Memot',
    'Ou Reang Ov',
    'Ponhea Kraek',
    'Tboung Khmum',
    'Krong Suong',
  ),
);

// Use this filter to handle the Commune of Cambodia
$places['KH'] = apply_filters('scpwoo_custom_places_kh', $places['KH']);