<?php

/**
 * $country places/cities/municipalities/districts
 * - $count places/cities/municipalities/districts
 * 
 * Source: 
 * - [Please add the source(s) link(s) to check the list of places]
 * 
 * @author  Your Name Here <yourname@here.com> | https://yourwebsite.com
 * @version 1.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 */

global $places;

$places['KH'] = array(  
  'KH12' => array(
    'Boeng Keng Kang Ti Muoy',
    'Boeng Keng Kang Ti Pir',
    'Boeng Keng Kang Ti Bei',
    'Olympic',
    'Tumnob Tuek',
    'Tuol Svay Prey Ti Muoy',
    'Tuol Svay Prey Ti Pir',
    'Tonle Basak',
    'Boeng Trabaek',
    'Phsar Daeum Thkov',
    'Tuol Tumpung Ti Muoy',
    'Tuol Tumpung Ti Pir',
    'Preaek Lieb',
    'Prek Ta Sek',
    'Chroy Changvar',
    'Bak Khaeng',
    'Koh Dach',
    'Chak Angrae Leu',
    'Chak Angrae Kraom',
    'Boeng Tumpun 1',
    'Boeng Tumpun 2',
    'Stueng Mean Chey 1',
    'Stueng Mean Chey 2',
    'Stueng Mean Chey 3',
    'Monorom',
    'Mittapheap',
    'Veal Vong',
    'Orussey I',
    'Orussey II',
    'Orussey III',
    'Orussey IV',
    'Boeung Prolit',
    'Svay Pak',
    'Chrang Chamreh I',
    'Kilomaetr 7',
    'Russey Keo',
    'Chrang Chamreh II',
    'Tuol Sangkae I',
    'Tuol Sangkae II',
    'Boeung Kak I',
    'Boeung Kak II',
    'Phsar Depo I',
    'Phsar Depo II',
    'Phsar Depo III',
    'Teuk Laak I',
    'Teuk Lak II',
    'Teuk Lak II',
    'Teuk Lak III',
    'Phsar Daeum Kor',
    'Boeung Salang',
    'Srah Chak',
    'Wat Phnom',
    'Phsar Chas',
    'Phsar Kandal I',
    'Phsar Kandal II',
    'Chaktomuk',
    'Phsar Thmey I',
    'Phsar Thmey II',
    'Phsar Thmey III',
    'Boeung Raing',
    'Chbar Ampov I',
    'Chbar Ampov II',
    'Nirouth',
    'Prek Aeng',
    'Kbal Koh',
    'Prek Thmei',
    'Dangkao',
    'Pong Tuek',
    'Prey Veaeng',
    'Prey Sa',
    'Spean Thma',
    'Cheung Aek',
    'Roluos',
    'Preaek Kampues',
    'Kong Noy',
    'Tien',
    'Sak Sampov',
    'Prateah Lang',
    'Krang Pongro',
    'Chaom Chau 1',
    'Kakab 1',
    'Kakab 2',
    'Chaom Chau 2',
    'Chaom Chau 3',
    'Trapeang Krasang',
    'Samraong Kraom',
    'Ponhea Pon',
    'Prek Pnov',
    'Samraong',
    'Kouk Roka',
    'Ponsang',
    'Phnom Penh Thmei',
    'Tuek Thla',
    'Krang Thnong',
    'Ou Baek K-Am',
    'Kouk Khleang',
  ),
);

// Use this filter to handle the Commune of Cambodia
$places['KH'] = apply_filters('scpwoo_custom_places_kh', $places['KH']);